# Just an example. Notifications must also be enabled on buckets.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  template:
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_NOTIFY_KAFKA_ENABLE
          value: "on"
        - name: MINIO_NOTIFY_KAFKA_BROKERS
          value: bootstrap.kafka:9092
        - name: MINIO_NOTIFY_KAFKA_TOPIC
          value: minio-notifications.stream.json
