apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: minio/mc
  newName: docker.io/minio/mc
  newTag: RELEASE.2021-11-05T10-05-06Z@sha256:d490755ededf4219f5d7abd313a3670813417635c60372cde441618c059b32ff

resources:
- bucket-create-job.yaml
