apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: minio/minio
  newName: ghcr.io/yolean/minio
  newTag: RELEASE.2025-07-18T21-56-31Z@sha256:da0fe26595711d0fb93dd28e24552520f68897195f4a23f5a17ffa9924ec3fac

resources:
- minio-hl-svc.yaml
- minio-statefulset.yaml
