apiVersion: v1
kind: Service
metadata:
  name: minio-hl-svc
  labels:
    v1beta1.min.io/instance: minio
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    v1beta1.min.io/instance: minio
  sessionAffinity: None
