apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: minio-hl-svc
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  replicas: 0
  selector:
    matchLabels:
      v1beta1.min.io/instance: minio
  template:
    metadata:
      labels:
        app: minio
        v1beta1.min.io/instance: minio
      annotations:
        prometheus.io/path: /minio/prometheus/metrics
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: minio
        image: docker.io/minio/minio:RELEASE.2020-11-13T20-10-18Z@sha256:9856a48ac93c32f72e4f161a327daba16cd5a9e3cbd037e08c94951622a25057
        args:
        - server
        env:
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: public
        - name: MINIO_BROWSER
          value: "off"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: secretkey
        ports:
        - containerPort: 9000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 20
        resources:
          requests:
            cpu: 10m
            memory: 25Mi
        volumeMounts:
        - mountPath: /export
          name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
